// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkbytFtbqyQxl0IZua_Oz5CqtSZN45G84',
    appId: '1:730981280068:web:0421e1cf1ec7e0993e0f11',
    messagingSenderId: '730981280068',
    projectId: 'healthcare-c3c7c',
    authDomain: 'healthcare-c3c7c.firebaseapp.com',
    storageBucket: 'healthcare-c3c7c.appspot.com',
    measurementId: 'G-D00QYZ2STN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRHnLnGnbK_LIkBJW1_9APLN2yE8x9HnM',
    appId: '1:730981280068:android:384ea609dc54a7b63e0f11',
    messagingSenderId: '730981280068',
    projectId: 'healthcare-c3c7c',
    storageBucket: 'healthcare-c3c7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsWQUC2X9qrmUqUlgVhCTsIxcyaQBVbFk',
    appId: '1:730981280068:ios:10fea3f8aa992eba3e0f11',
    messagingSenderId: '730981280068',
    projectId: 'healthcare-c3c7c',
    storageBucket: 'healthcare-c3c7c.appspot.com',
    iosBundleId: 'com.example.clearanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsWQUC2X9qrmUqUlgVhCTsIxcyaQBVbFk',
    appId: '1:730981280068:ios:dd772ec7de6ca23f3e0f11',
    messagingSenderId: '730981280068',
    projectId: 'healthcare-c3c7c',
    storageBucket: 'healthcare-c3c7c.appspot.com',
    iosBundleId: 'com.example.clearanceSystem.RunnerTests',
  );
}
